# Generated by Django 2.0.5 on 2018-06-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Hashtags',
            new_name='Hashtag',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
