# Generated by Django 2.0.5 on 2018-06-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180616_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='hastags',
            new_name='hastag',
        ),
    ]
