# Generated by Django 2.0.5 on 2018-06-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20180616_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='hastag',
            new_name='hashtag',
        ),
    ]
