# Generated by Django 2.0.5 on 2018-08-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
